name: sage-build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - compilers<=1.6.0
  - make
  - m4
  - perl
  - python
  - tar
  - bc
  - appdirs
  - boost-cpp
  - brial
  - bzip2
  - cddlib
  - cliquer
  - cmake
  - curl
  - distlib
  - ecl
  - eclib
  - ecm
  - fflas-ffpack
  - filelock
  - libflint
  - fplll
  - freetype
  - gap-defaults>=4.12.2
  - bdw-gc
  - gengetopt
  - gf2x
  - gfan
  - fortran-compiler
  - giac
  - givaro
  - glpk
  - gmp
  - gsl
  - iml
  - texinfo
  - lcalc
  - libatomic_ops
  - libbraiding
  - libffi
  - libgd
  - libhomfly
  - xz
  - libpng
  - linbox
  - lrcalc
  - m4ri
  - m4rie
  - mathjax
  - maxima
  - mpc
  - mpfi
  - mpfr
  - nauty
  - ncurses
  - ninja
  - ntl
  - openblas
  - blas=2.*=openblas
  - openssl
  - palp
  - pari=*=*_pthread
  - pari-elldata
  - pari-galdata
  - pari-galpol
  - pari-seadata
  - pari-galdata
  - pari-seadata-small
  - patch
  - pkg-config
  - planarity
  - ppl
  - primecount
  - primesieve
  - qhull
  - readline
  - rw
  - singular
  - sqlite
  - suitesparse
  - symmetrica
  - sympow
  - tachyon
  - tox
  - virtualenv
  - xz
  - zeromq
  - zlib
  # Packages needed for ./bootstrap
  - autoconf
  - automake
  - libtool
  - pkg-config
  # optional packages
  - 4ti2
  - bliss
  - coincbc
  - imageio-ffmpeg
  - open-fonts
  - graphviz
  - igraph
  - imagemagick
  - isl
  - graphviz
  - libsemigroups
  - lrslib
  - tbb
  - pandoc
  - pari-elldata
  - pari-galpol
  - pari-nftables
  - pari-seadata
  - pdf2svg
  - r
  - r-essentials
  - symengine
