name: sage
channels:
  - conda-forge
  - nodefaults
dependencies:
  - compilers<=1.6.0
  - make
  - m4
  - perl
  - python
  - tar
  - bc
  - appdirs
  - boost-cpp
  - brial
  - bzip2
  - cddlib
  - cliquer
  - cmake
  - curl
  - distlib
  - ecl
  - eclib
  - ecm
  - fflas-ffpack
  - filelock
  - libflint
  - fplll
  - freetype
  - gap-defaults>=4.12.2
  - bdw-gc
  - gengetopt
  - gf2x
  - gfan
  - fortran-compiler
  - giac
  - givaro
  - glpk
  - gmp
  - gsl
  - iml
  - texinfo
  - lcalc
  - libatomic_ops
  - libbraiding
  - libffi
  - libgd
  - libhomfly
  - xz
  - libpng
  - linbox
  - lrcalc
  - m4ri
  - m4rie
  - mathjax
  - maxima
  - mpc
  - mpfi
  - mpfr
  - nauty
  - ncurses
  - ninja
  - ntl
  - openblas
  - blas=2.*=openblas
  - openssl
  - palp
  - pari=*=*_pthread
  - pari-elldata
  - pari-galdata
  - pari-galpol
  - pari-seadata
  - pari-galdata
  - pari-seadata-small
  - patch
  - pkg-config
  - planarity
  - ppl
  - primecount
  - primesieve
  - qhull
  - readline
  - rw
  - singular
  - sqlite
  - suitesparse
  - symmetrica
  - sympow
  - tachyon
  - tox
  - virtualenv
  - xz
  - zeromq
  - zlib
  # Packages needed for ./bootstrap
  - autoconf
  - automake
  - libtool
  - pkg-config
  # Additional packages providing all dependencies for the Sage library
  - alabaster
  - appnope
  - argon2-cffi
  - asttokens
  - attrs
  - babel
  - beautifulsoup4
  - beniget
  - bleach
  - certifi
  - cffi
  - charset-normalizer
  - sagemath-db-combinatorial-designs
  - conway-polynomials
  - cppy
  - cvxopt
  - cycler
  - cypari2
  - cysignals
  - cython>=3.0,!=3.0.3,<4.0
  - python-dateutil
  - debugpy
  - decorator
  - defusedxml
  - docutils
  - editables
  - sagemath-db-elliptic-curves
  - entrypoints
  - executing
  - python-fastjsonschema
  - flit-core
  - fonttools
  - fpylll>=0.5.9
  - furo
  - gast
  - gmpy2
  - sagemath-db-graphs
  - hatchling
  - idna
  - imagesize
  - importlib_metadata
  - importlib-resources
  - ipykernel
  - ipympl
  - ipython
  - ipython_genutils
  - ipywidgets>=7.5.1
  - jedi
  - jinja2
  - jmol
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter-jsmol
  - jupyter_sphinx
  - jupyterlab
  - jupyterlab_pygments
  - kiwisolver
  - python-lrcalc~=2.1
  - markupsafe
  - matplotlib>=3.5.1
  - matplotlib-inline
  - memory-allocator
  - mistune
  - mpmath
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx<3.3,>=2.4
  - notebook
  - numpy
  - packaging
  - pandocfilters
  - parso
  - pathspec
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgconfig
  - platformdirs
  - pluggy
  - ply
  - sagemath-db-polytopes
  - pplpy
  - primecountpy
  - prometheus_client
  - prompt_toolkit>=3.0.38
  - pure_eval
  - py
  - pybind11
  - pycparser
  - pygments
  - pyparsing
  - pyrsistent
  - pythran
  - pytz
  - pytz-deprecation-shim
  - pyzmq
  - requests
  - rpy2
  - sagetex
  - scipy<1.12,>=1.5
  - send2trash
  - setuptools
  - setuptools_scm
  - six
  - snowballstemmer
  - soupsieve
  - sphinx>=5.2
  - sphinx-basic-ng
  - sphinx-copybutton
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - stack_data
  - sympy
  - terminado
  - threejs-sage=122.*
  - tinycss2
  - tomli
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - tzlocal
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - zipp
  # optional packages
  - 4ti2
  - bliss
  - coincbc
  - imageio-ffmpeg
  - open-fonts
  - graphviz
  - igraph
  - imagemagick
  - isl
  - graphviz
  - libsemigroups
  - lrslib
  - tbb
  - pandoc
  - pari-elldata
  - pari-galpol
  - pari-nftables
  - pari-seadata
  - pdf2svg
  - r
  - r-essentials
  - symengine
  - biopython
  - ccache
  - cryptominisat
  - cvxpy
  - dot2tex
  - dsdp
  - libeantic
  - ecos
  - gap
  - gap
  - latte-integrale
  - libogg
  - libtheora
  - mathics3
  - nibabel
  - normaliz
  - notedown
  - osqp
  - palettable
  - pandoc-attributes
  - pari_jupyter
  - pint
  - pybtex
  - pycosat
  - cryptominisat
  - pygraphviz
  - pynormaliz
  - pyppeteer
  - pyscipopt
  - pysingular
  - build
  - python-igraph
  - qdldl-python
  - rubiks
  - sagemath-bliss
  - sagemath-sirocco
  - scip
  - scs
  - jupyter-kernel-singular
  - sirocco
  - soplex
  - sqlalchemy
  - python-symengine
  - texttable
  - pip:
